@props(['title', 'subtitle' => null, 'icon' => 'fa-pen-to-square', 'fields' => [], 'actionRoute' => null, 'backRoute' => null, 'record' => null, 'editing' => false, 'submitLabel' => 'حفظ البيانات'])
@php($actionExists = $actionRoute && \Illuminate\Support\Facades\Route::has($actionRoute))
<x-page-header :title="$title" :subtitle="$subtitle" eyebrow="إدارة البيانات" :icon="$icon"><x-slot:actions>@if($backRoute && \Illuminate\Support\Facades\Route::has($backRoute))<a href="{{ route($backRoute) }}" class="app-btn app-btn-secondary"><i class="fa-solid fa-arrow-right"></i> العودة للقائمة</a>@endif</x-slot:actions></x-page-header>
<div class="mx-auto max-w-4xl"><x-panel :title="$title" subtitle="أدخل البيانات المطلوبة ثم راجعها قبل الحفظ" :icon="$icon"><form method="POST" action="{{ $actionExists ? ($editing ? route($actionRoute, $record) : route($actionRoute)) : '#' }}">@csrf @if($editing)@method('PUT')@endif
<div class="grid gap-x-5 gap-y-4 md:grid-cols-2">@foreach($fields as $field)@php($fieldName = $field['name'])@php($fieldValue = old($fieldName, data_get($record, $fieldName)))<div @class(['md:col-span-2' => ($field['full'] ?? false)])>
@if(($field['type'] ?? 'text') === 'textarea')<x-textarea-field :label="$field['label']" :name="$fieldName" :value="$fieldValue" :required="$field['required'] ?? false" :rows="$field['rows'] ?? 4" :placeholder="$field['placeholder'] ?? null" />
@elseif(($field['type'] ?? '') === 'select')<x-select-field :label="$field['label']" :name="$fieldName" :value="$fieldValue" :options="$field['options'] ?? []" :required="$field['required'] ?? false" :placeholder="$field['placeholder'] ?? 'اختر...'" />
@elseif(($field['type'] ?? '') === 'checkbox')<label class="flex items-center gap-3 rounded-xl border border-line p-3"><input type="checkbox" name="{{ $fieldName }}" value="1" @checked((bool)$fieldValue) class="rounded border-line text-brand focus:ring-brand/30"><span class="text-[11px] font-bold">{{ $field['label'] }}</span></label>
@else<x-form-field :label="$field['label']" :name="$fieldName" :type="$field['type'] ?? 'text'" :value="$fieldValue" :required="$field['required'] ?? false" :placeholder="$field['placeholder'] ?? null" :help="$field['help'] ?? null" />@endif
</div>@endforeach</div>
<div class="mt-7 flex flex-wrap items-center gap-2 border-t border-line pt-5">@if($actionExists)<button type="submit" class="app-btn app-btn-primary"><i class="fa-solid fa-floppy-disk"></i> {{ $submitLabel }}</button>@else<button type="button" disabled class="app-btn cursor-not-allowed bg-surface-raised text-dim"><i class="fa-solid fa-link-slash"></i> الحفظ غير متاح حتى ربط المسار</button>@endif @if($backRoute && \Illuminate\Support\Facades\Route::has($backRoute))<a href="{{ route($backRoute) }}" class="app-btn app-btn-secondary">إلغاء</a>@endif</div>
@if(!$actionExists)<div class="mt-4 rounded-xl border border-warning/20 bg-warning/10 p-3 text-[10px] leading-5 text-warning"><i class="fa-solid fa-circle-info ml-1"></i> هذه الواجهة جاهزة بصريًا، لكن مسار الحفظ غير مسجل حاليًا في routes/web.php؛ تم تعطيل الإرسال لتجنب طلب غير صالح.</div>@endif
</form></x-panel></div>
