@extends('layouts.app')
@section('title', 'استيراد البيانات')
@section('topbar-title', 'استيراد البيانات')
@section('content')
<x-page-header title="استيراد البيانات" subtitle="رفع ملف المحفظة ومراجعة الصفوف قبل بدء المعالجة." eyebrow="المحافظ والمؤسسات" icon="fa-file-import" />
<div class="grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(280px,.8fr)]">
<x-panel title="رفع ملف محفظة" subtitle="تأكد من صحة الملف قبل الإرسال" icon="fa-cloud-arrow-up"><form method="POST" action="{{ \Illuminate\Support\Facades\Route::has('banks.scope.store') ? route('banks.scope.store') : (\Illuminate\Support\Facades\Route::has('banks.scope.import.store') ? route('banks.scope.import.store') : '#') }}" enctype="multipart/form-data" class="space-y-5">@csrf
<label class="block"><span class="app-label">البنك / المؤسسة <span class="text-danger">*</span></span><select name="bank_id" class="app-input" required><option value="">اختر البنك</option>@foreach(($banks ?? collect()) as $bank)<option value="{{ $bank->id }}" @selected(old('bank_id') == $bank->id)>{{ $bank->name }}</option>@endforeach</select>@error('bank_id')<span class="form-error">{{ $message }}</span>@enderror</label>
<label class="block"><span class="app-label">ملف البيانات <span class="text-danger">*</span></span><span class="dropzone"><i class="fa-solid fa-file-csv text-2xl text-brand"></i><span class="font-extrabold text-fg">اختر ملف CSV أو Excel</span><span class="text-[10px]">تأكد أن عناوين الأعمدة مطابقة لقالب الاستيراد</span><input class="mt-3 block w-full max-w-xs text-xs" type="file" name="file" accept=".csv,.xlsx,.xls,.txt" required></span>@error('file')<span class="form-error">{{ $message }}</span>@enderror</label>
<label class="block"><span class="app-label">ملاحظات الاستيراد</span><textarea class="app-input" name="notes" rows="3" maxlength="1000" placeholder="معلومات تساعد على تتبع عملية الاستيراد">{{ old('notes') }}</textarea></label>
<div class="rounded-xl border border-warning/20 bg-warning/5 p-3 text-[11px] leading-6 text-warning"><i class="fa-solid fa-triangle-exclamation ml-1"></i> راجع الملف قبل الإرسال وتأكد من عدم تكرار البيانات. يعتمد قبول الملف على قواعد التحقق في الخادم.</div>
<button type="submit" @if(!\Illuminate\Support\Facades\Route::has('banks.scope.store') && !\Illuminate\Support\Facades\Route::has('banks.scope.import.store')) disabled @endif class="app-btn app-btn-primary"><i class="fa-solid fa-upload"></i> رفع الملف وبدء المراجعة</button>
</form></x-panel>
<div class="space-y-5"><x-panel title="خطوات الاستيراد" subtitle="سير العمل" icon="fa-list-check"><ol class="space-y-4">@foreach([['1','اختيار المؤسسة','حدد البنك أو الجهة المالكة للمحفظة.'],['2','رفع الملف','استخدم ملفًا منسقًا وراجع عناوين الأعمدة.'],['3','التحقق','تُراجع البيانات المطلوبة والمفاتيح المكررة.'],['4','اعتماد النتائج','راجع الأخطاء قبل تفعيل المحفظة.']] as $step)<li class="flex gap-3"><span class="grid h-8 w-8 shrink-0 place-items-center rounded-xl border border-brand/20 bg-brand/10 text-xs font-black text-brand">{{ $step[0] }}</span><div><p class="text-xs font-extrabold text-fg">{{ $step[1] }}</p><p class="mt-1 text-[10px] leading-5 text-muted">{{ $step[2] }}</p></div></li>@endforeach</ol></x-panel>
<x-panel title="عمليات الاستيراد الأخيرة" subtitle="آخر الملفات التي تمت معالجتها" icon="fa-clock-rotate-left" :padding="false"><div class="divide-y divide-line">@forelse(($imports ?? collect())->take(5) as $import)<div class="flex items-center justify-between gap-3 p-4"><div class="min-w-0"><p class="truncate text-xs font-bold text-fg">{{ $import->original_filename ?? 'ملف استيراد' }}</p><p class="mt-1 text-[10px] text-muted">{{ $import->created_at?->format('Y-m-d H:i') ?? '—' }}</p></div><x-status-badge :status="$import->status ?? 'pending'" /></div>@empty<div class="p-4 text-center text-xs text-muted">لا توجد عمليات استيراد سابقة.</div>@endforelse</div></x-panel></div></div>
@endsection
