@extends('layouts.app')
@section('title', 'العملاء')
@section('content')
<x-page-header title="العملاء" subtitle="إدارة ملفات العملاء وبيانات التواصل والهوية في مكان واحد." eyebrow="إدارة العملاء" icon="fa-users">
    <x-slot:actions><a href="{{ route('clients.create') }}" class="app-btn app-btn-primary"><i class="fa-solid fa-user-plus"></i> إضافة عميل جديد</a></x-slot:actions>
</x-page-header>
<div class="mb-5 grid gap-3 sm:grid-cols-3"><div class="app-card flex items-center gap-3 p-4"><span class="grid h-10 w-10 place-items-center rounded-xl bg-brand/10 text-brand"><i class="fa-solid fa-users"></i></span><div><p class="text-[10px] font-bold text-dim">النتائج المعروضة</p><p class="mt-1 text-lg font-extrabold">{{ number_format($clients->total() ?? $clients->count()) }}</p></div></div><div class="app-card flex items-center gap-3 p-4 sm:col-span-2"><i class="fa-solid fa-circle-info text-brand"></i><p class="text-[10px] leading-5 text-muted">ابحث بالاسم أو كود العميل أو الرقم القومي. يتم عرض النتائج على صفحات لتسهيل التعامل مع السجلات الكبيرة.</p></div></div>
<x-panel title="دليل العملاء" subtitle="استخدم البحث للوصول السريع إلى سجل العميل" icon="fa-address-book" :padding="false">
    <x-slot:actions><form method="GET" action="{{ route('clients.index') }}" class="flex w-full flex-wrap gap-2 sm:w-auto"><div class="relative min-w-[220px] flex-1 sm:flex-none"><i class="fa-solid fa-magnifying-glass absolute right-3 top-1/2 -translate-y-1/2 text-[11px] text-dim"></i><input class="app-input pr-9 sm:w-72" name="q" value="{{ request('q') }}" placeholder="الاسم، الكود، الرقم القومي"></div><button class="app-btn app-btn-secondary"><i class="fa-solid fa-filter"></i> بحث</button>@if(request()->filled('q'))<a href="{{ route('clients.index') }}" class="app-btn app-btn-secondary">مسح</a>@endif</form></x-slot:actions>
    <div class="overflow-x-auto"><table class="app-table"><thead><tr><th>العميل</th><th>كود العميل</th><th>الرقم القومي</th><th>المحافظة</th><th>تاريخ الإضافة</th><th class="text-center">الإجراءات</th></tr></thead><tbody>
    @forelse($clients as $client)<tr><td><div class="flex items-center gap-3"><x-avatar :name="$client->name" size="sm"/><div><a href="{{ route('clients.show', $client) }}" class="text-xs font-extrabold text-fg hover:text-brand">{{ $client->name }}</a><p class="mt-1 text-[9px] text-dim">{{ $client->email ?? 'لا يوجد بريد إلكتروني' }}</p></div></div></td><td><span class="rounded-lg bg-white/[0.025] px-2 py-1 font-mono text-[10px] font-bold text-muted">{{ $client->code }}</span></td><td class="font-mono text-muted">{{ $client->national_id }}</td><td>{{ $client->governorate?->name ?? '—' }}</td><td class="whitespace-nowrap text-muted">{{ $client->created_at?->format('Y-m-d') ?? '—' }}</td><td><div class="flex items-center justify-center gap-1"><x-action-icon :href="route('clients.show', $client)" icon="fa-eye" label="عرض" tone="green"/><x-action-icon :href="route('clients.edit', $client)" icon="fa-pen" label="تعديل"/><form method="POST" action="{{ route('clients.destroy', $client) }}" onsubmit="return confirm('هل تريد حذف هذا العميل؟')">@csrf @method('DELETE')<button class="inline-grid h-8 w-8 place-items-center rounded-lg border border-danger/20 bg-danger/10 text-[11px] text-danger" title="حذف" aria-label="حذف"><i class="fa-solid fa-trash"></i></button></form></div></td></tr>
    @empty<tr><td colspan="6"><x-empty-state title="لا توجد سجلات مطابقة" description="غيّر كلمات البحث أو ابدأ بإضافة عميل جديد." icon="fa-users"><x-slot:action><a href="{{ route('clients.create') }}" class="app-btn app-btn-primary"><i class="fa-solid fa-plus"></i> إضافة عميل</a></x-slot:action></x-empty-state></td></tr>@endforelse
    </tbody></table></div>
    @if(method_exists($clients, 'links'))<div class="flex flex-wrap items-center justify-between gap-3 border-t border-line px-5 py-4"><p class="text-[10px] text-dim">عرض {{ $clients->firstItem() ?? 0 }}–{{ $clients->lastItem() ?? 0 }} من {{ $clients->total() ?? 0 }} سجل</p><div class="text-xs">{{ $clients->links() }}</div></div>@endif
</x-panel>
@endsection
