@extends('layouts.app')
@section('title', $client->name)
@section('content')
<x-page-header :title="$client->name" subtitle="ملف العميل والبيانات المرتبطة به." eyebrow="العملاء / الملف الشخصي" icon="fa-address-card"><x-slot:actions><a href="{{ route('clients.edit', $client) }}" class="app-btn app-btn-primary"><i class="fa-solid fa-pen"></i> تعديل البيانات</a><a href="{{ route('clients.index') }}" class="app-btn app-btn-secondary"><i class="fa-solid fa-arrow-right"></i> كل العملاء</a></x-slot:actions></x-page-header>
<div class="mb-5 grid gap-4 sm:grid-cols-3"><div class="app-stat"><p class="app-stat-label">كود العميل</p><p class="app-stat-value mt-2 font-mono">{{ $client->code }}</p><p class="mt-2 text-[10px] text-dim">معرّف داخلي فريد</p></div><div class="app-stat"><p class="app-stat-label">القضايا المرتبطة</p><p class="app-stat-value mt-2">{{ $client->debtCases?->count() ?? 0 }}</p><p class="mt-2 text-[10px] text-dim">جميع القضايا المرتبطة بالعميل</p></div><div class="app-stat"><p class="app-stat-label">تاريخ إنشاء الملف</p><p class="mt-2 text-lg font-extrabold">{{ $client->created_at?->format('Y-m-d') ?? '—' }}</p><p class="mt-2 text-[10px] text-dim">آخر تحديث: {{ $client->updated_at?->format('Y-m-d') ?? '—' }}</p></div></div>
<div class="grid gap-5 xl:grid-cols-2"><x-panel title="البيانات الأساسية" subtitle="معلومات الهوية والعمل والعنوان" icon="fa-id-card"><dl class="grid gap-4 sm:grid-cols-2"><div><dt class="text-[10px] font-bold text-dim">الرقم القومي</dt><dd class="mt-1 text-xs font-extrabold text-fg">{{ $client->national_id }}</dd></div><div><dt class="text-[10px] font-bold text-dim">البريد الإلكتروني</dt><dd class="mt-1 break-all text-xs font-bold text-fg">{{ $client->email ?? 'غير مسجل' }}</dd></div><div><dt class="text-[10px] font-bold text-dim">المحافظة</dt><dd class="mt-1 text-xs font-bold text-fg">{{ $client->governorate?->name ?? 'غير محددة' }}</dd></div><div><dt class="text-[10px] font-bold text-dim">جهة العمل</dt><dd class="mt-1 text-xs font-bold text-fg">{{ $client->employer_name ?? 'غير مسجلة' }}</dd></div><div><dt class="text-[10px] font-bold text-dim">المسمى الوظيفي</dt><dd class="mt-1 text-xs font-bold text-fg">{{ $client->job_title ?? 'غير مسجل' }}</dd></div><div class="sm:col-span-2"><dt class="text-[10px] font-bold text-dim">عنوان السكن</dt><dd class="mt-1 text-xs leading-6 text-fg">{{ $client->address ?? 'غير مسجل' }}</dd></div><div class="sm:col-span-2"><dt class="text-[10px] font-bold text-dim">عنوان العمل</dt><dd class="mt-1 text-xs leading-6 text-fg">{{ $client->work_address ?? 'غير مسجل' }}</dd></div>@if($client->notes)<div class="sm:col-span-2"><dt class="text-[10px] font-bold text-dim">ملاحظات</dt><dd class="mt-1 whitespace-pre-line text-xs leading-6 text-fg">{{ $client->notes }}</dd></div>@endif</dl></x-panel>
<x-panel title="أرقام الهاتف" subtitle="أرقام التواصل المسجلة لهذا العميل" icon="fa-phone"><x-slot:actions><span class="rounded-lg bg-white/[0.025] px-2 py-1 text-[10px] font-bold text-muted">{{ $client->phones?->count() ?? 0 }} رقم</span></x-slot:actions>@forelse($client->phones as $phone)<div class="flex items-center justify-between gap-3 border-b border-line py-3 last:border-0"><div class="flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-xl bg-info/10 text-info"><i class="fa-solid fa-phone"></i></span><div><p class="font-mono text-xs font-extrabold">{{ $phone->phone }}</p><p class="mt-1 text-[10px] text-dim">{{ ['primary'=>'أساسي','alternate'=>'بديل','work'=>'العمل','other'=>'أخرى'][$phone->label] ?? $phone->label }}</p></div></div><x-status-badge :status="$phone->is_valid ? 'active' : 'inactive'" /></div>@empty<x-empty-state title="لا توجد أرقام مسجلة" description="يمكن إضافة أرقام التواصل عند تفعيل إدارة أرقام الهاتف." icon="fa-phone-slash"/>@endforelse</x-panel></div>
<div class="mt-5"><x-panel title="القضايا المرتبطة" subtitle="ملخص القروض والقضايا المسجلة للعميل" icon="fa-file-invoice-dollar" :padding="false"><div class="overflow-x-auto"><table class="app-table"><thead><tr><th>رقم القرض</th><th>الحالة</th><th>إجمالي الدين</th><th>المتأخر</th><th>المحصل</th></tr></thead><tbody>@forelse($client->debtCases as $case)<tr><td class="font-bold">{{ $case->loan_number ?? '—' }}</td><td><x-status-badge :status="$case->status" /></td><td class="font-extrabold">{{ number_format((float)$case->total_debt,2) }} ج.م</td><td>{{ number_format((float)$case->overdue_amount,2) }} ج.م</td><td class="font-extrabold text-brand">{{ number_format((float)$case->collected_amount,2) }} ج.م</td></tr>@empty<tr><td colspan="5"><x-empty-state title="لا توجد قضايا مرتبطة" description="ستظهر القضايا المرتبطة بهذا العميل هنا." icon="fa-file-circle-question"/></td></tr>@endforelse</tbody></table></div></x-panel></div>
@endsection
