@extends('layouts.app')
@section('title', 'المدفوعات')
@section('content')
<x-page-header title="المدفوعات" subtitle="سجل عمليات التحصيل وحالات التأكيد والرفض." eyebrow="إدارة التحصيل" icon="fa-money-bill-transfer"><x-slot:actions><a href="{{ route('payments.confirmations') }}" class="app-btn app-btn-secondary"><i class="fa-solid fa-clock"></i> مراجعة المعلّق</a><a href="{{ route('payments.create') }}" class="app-btn app-btn-primary"><i class="fa-solid fa-plus"></i> تسجيل دفعة</a></x-slot:actions></x-page-header>
<div class="mb-5 grid gap-3 sm:grid-cols-3"><div class="app-card flex items-center gap-3 p-4"><span class="grid h-10 w-10 place-items-center rounded-xl bg-warning/10 text-warning"><i class="fa-solid fa-hourglass-half"></i></span><div><p class="text-[10px] font-bold text-dim">قيد المراجعة</p><p class="mt-1 text-lg font-extrabold">{{ isset($payments) ? $payments->where('status','pending')->count() : 0 }}</p></div></div><div class="app-card flex items-center gap-3 p-4"><span class="grid h-10 w-10 place-items-center rounded-xl bg-brand/10 text-brand"><i class="fa-solid fa-circle-check"></i></span><div><p class="text-[10px] font-bold text-dim">مؤكدة في الصفحة الحالية</p><p class="mt-1 text-lg font-extrabold">{{ isset($payments) ? $payments->where('status','confirmed')->count() : 0 }}</p></div></div><div class="app-card flex items-center gap-3 p-4"><span class="grid h-10 w-10 place-items-center rounded-xl bg-danger/10 text-danger"><i class="fa-solid fa-circle-xmark"></i></span><div><p class="text-[10px] font-bold text-dim">مرفوضة في الصفحة الحالية</p><p class="mt-1 text-lg font-extrabold">{{ isset($payments) ? $payments->where('status','rejected')->count() : 0 }}</p></div></div></div>
<x-panel title="سجل المدفوعات" subtitle="صفِّ حسب الحالة أو افتح تفاصيل أي إيصال" icon="fa-receipt" :padding="false"><x-slot:actions><form method="GET" action="{{ route('payments.index') }}" class="flex flex-wrap gap-2"><select name="status" class="app-input min-w-[150px]"><option value="">كل الحالات</option>@foreach(['pending'=>'قيد المراجعة','confirmed'=>'مؤكدة','rejected'=>'مرفوضة'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select><button class="app-btn app-btn-secondary"><i class="fa-solid fa-filter"></i> تطبيق</button></form></x-slot:actions>
<div class="overflow-x-auto"><table class="app-table"><thead><tr><th>الإيصال</th><th>العميل / القضية</th><th>المحصل</th><th>المبلغ</th><th>طريقة الدفع</th><th>الحالة</th><th>تاريخ الدفع</th><th></th></tr></thead><tbody>@forelse($payments as $payment)<tr><td><span class="font-mono text-[10px] font-extrabold text-fg">{{ $payment->receipt_number }}</span></td><td><p class="text-xs font-extrabold">{{ $payment->debtCase?->client?->name ?? '—' }}</p><p class="mt-1 text-[9px] text-dim">{{ $payment->debtCase?->loan_number ?? ('قضية #'.$payment->debt_case_id) }}</p></td><td>{{ $payment->collector?->name ?? '—' }}</td><td class="whitespace-nowrap font-extrabold">{{ number_format((float)$payment->amount,2) }} <small class="text-dim">ج.م</small></td><td>{{ ['cash'=>'نقدي','e_wallet'=>'محفظة إلكترونية','bank_transfer'=>'تحويل بنكي','card'=>'بطاقة','cheque'=>'شيك'][$payment->method] ?? $payment->method }}</td><td><x-status-badge :status="$payment->status" /></td><td class="whitespace-nowrap text-muted">{{ $payment->paid_at?->format('Y-m-d H:i') ?? '—' }}</td><td><x-action-icon :href="route('payments.show',$payment)" icon="fa-eye" label="تفاصيل" tone="green"/></td></tr>@empty<tr><td colspan="8"><x-empty-state title="لا توجد مدفوعات" description="لم يتم العثور على مدفوعات مطابقة لعوامل التصفية." icon="fa-receipt"><x-slot:action><a href="{{ route('payments.create') }}" class="app-btn app-btn-primary">تسجيل دفعة</a></x-slot:action></x-empty-state></td></tr>@endforelse</tbody></table></div>
@if(method_exists($payments,'links'))<div class="flex flex-wrap items-center justify-between gap-3 border-t border-line px-5 py-4"><p class="text-[10px] text-dim">{{ $payments->total() }} سجل · الصفحة {{ $payments->currentPage() }} من {{ $payments->lastPage() }}</p>{{ $payments->links() }}</div>@endif
</x-panel>
@endsection
