@extends('layouts.app')
@section('title', 'مركز العمليات')
@section('topbar-title', 'مركز العمليات')
@section('content')
<x-page-header title="مركز العمليات" subtitle="نقطة متابعة الأعمال التي تحتاج إلى قرار أو استكمال من فريق التحصيل." eyebrow="الرئيسية" icon="fa-layer-group" />
@php($pendingPayments = $pendingPayments ?? collect()) @php($overduePromises = $overduePromises ?? collect()) @php($openComplaints = $openComplaints ?? collect()) @php($upcomingVisits = $upcomingVisits ?? collect())
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><x-stat-card label="مدفوعات تنتظر المراجعة" :value="number_format(method_exists($pendingPayments,'count') ? $pendingPayments->count() : 0)" icon="fa-receipt" color="orange" hint="تأكيد أو رفض"/><x-stat-card label="وعود تحتاج متابعة" :value="number_format(method_exists($overduePromises,'count') ? $overduePromises->count() : 0)" icon="fa-handshake" color="purple" hint="مواعيد مستحقة أو متأخرة"/><x-stat-card label="شكاوى مفتوحة" :value="number_format(method_exists($openComplaints,'count') ? $openComplaints->count() : 0)" icon="fa-message" color="blue" hint="تحتاج معالجة"/><x-stat-card label="زيارات قادمة" :value="number_format(method_exists($upcomingVisits,'count') ? $upcomingVisits->count() : 0)" icon="fa-location-dot" color="green" hint="مواعيد ميدانية مجدولة"/></div>
<div class="mt-5 grid gap-5 xl:grid-cols-2"><x-panel title="المدفوعات المعلقة" subtitle="أولوية المراجعة المالية" icon="fa-clock" :padding="false"><div class="divide-y divide-line">@forelse($pendingPayments as $payment)<div class="flex flex-wrap items-center justify-between gap-3 p-4"><div><p class="text-xs font-extrabold text-fg">{{ $payment->receipt_number ?? ('دفعة #'.$payment->id) }}</p><p class="mt-1 text-[10px] text-muted">{{ $payment->debtCase?->client?->name ?? 'عميل غير محدد' }} · {{ number_format((float)($payment->amount ?? 0),2) }} ج.م</p></div>@if(\Illuminate\Support\Facades\Route::has('payments.show'))<a class="app-btn app-btn-secondary" href="{{ route('payments.show',$payment) }}">مراجعة</a>@endif</div>@empty<div class="p-4 text-xs text-muted">لا توجد مدفوعات معلقة مرسلة إلى الصفحة.</div>@endforelse</div></x-panel>
<x-panel title="الشكاوى المفتوحة" subtitle="تابع الحالات ذات الأولوية" icon="fa-message" :padding="false"><div class="divide-y divide-line">@forelse($openComplaints as $complaint)<div class="flex flex-wrap items-center justify-between gap-3 p-4"><div><p class="text-xs font-extrabold text-fg">{{ $complaint->reference_number ?? ('شكوى #'.$complaint->id) }} · {{ $complaint->subject ?? 'بدون عنوان' }}</p><p class="mt-1 text-[10px] text-muted">{{ $complaint->client?->name ?? 'عميل غير محدد' }} · الموعد {{ $complaint->due_at?->format('Y-m-d') ?? 'غير محدد' }}</p></div><x-status-badge :status="$complaint->status ?? 'open'" /></div>@empty<div class="p-4 text-xs text-muted">لا توجد شكاوى مفتوحة مرسلة إلى الصفحة.</div>@endforelse</div></x-panel></div>
@endsection
