@extends('layouts.app')
@section('title', 'الإشعارات')
@section('topbar-title', 'الإشعارات')
@section('content')
@php($records = $notifications ?? $items ?? auth()->user()?->notifications ?? collect())
<x-page-header title="الإشعارات" subtitle="تابع التنبيهات المتعلقة بالمدفوعات والوعود والمهام والتغييرات المهمة." eyebrow="الفريق والإدارة" icon="fa-bell"><x-slot:actions>@if(\Illuminate\Support\Facades\Route::has('notifications.read-all'))<form method="POST" action="{{ route('notifications.read-all') }}">@csrf<button class="app-btn app-btn-secondary"><i class="fa-solid fa-check-double"></i> تحديد الكل كمقروء</button></form>@endif</x-slot:actions></x-page-header>
<div class="app-card divide-y divide-line">@forelse($records as $notification)@php($payload = is_array($notification->data ?? null) ? $notification->data : (array)($notification->data ?? []))<article class="flex gap-3 p-4 sm:p-5"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-xl {{ ($notification->read_at ?? null) ? 'bg-white/[0.03] text-muted' : 'bg-brand/10 text-brand' }}"><i class="fa-solid fa-bell"></i></span><div class="min-w-0 flex-1"><div class="flex flex-wrap items-start justify-between gap-2"><h2 class="text-xs font-extrabold text-fg">{{ data_get($payload, 'title', data_get($payload, 'message', 'إشعار من النظام')) }}</h2><span class="text-[10px] text-dim">{{ $notification->created_at?->format('Y-m-d H:i') ?? '—' }}</span></div><p class="mt-1 text-[11px] leading-6 text-muted">{{ data_get($payload, 'body', data_get($payload, 'description', '')) }}</p>@if(!($notification->read_at ?? null))<span class="mt-2 inline-flex items-center gap-1.5 text-[9px] font-bold text-brand"><span class="h-1.5 w-1.5 rounded-full bg-brand"></span> غير مقروء</span>@endif</div>@if(\Illuminate\Support\Facades\Route::has('notifications.read') && !($notification->read_at ?? null))<form method="POST" action="{{ route('notifications.read', $notification->id) }}">@csrf<button class="app-btn app-btn-ghost">تعليم كمقروء</button></form>@endif</article>@empty<x-empty-state title="أنت على اطلاع" description="لا توجد إشعارات لعرضها حاليًا. ستظهر هنا التنبيهات الجديدة عند ورودها." icon="fa-bell-slash"/>@endforelse</div>
@if(is_object($records) && method_exists($records, 'links'))<div class="mt-4">{{ $records->links() }}</div>@endif
@endsection
