@extends('layouts.app')
@section('title', 'نظرة عامة')
@section('topbar-title', 'نظرة عامة')
@section('content')
<x-page-header title="نظرة عامة" subtitle="ملخص تشغيلي يجمع مؤشرات العملاء والقضايا والمدفوعات والالتزامات." eyebrow="الرئيسية" icon="fa-compass" />
@php($overviewStats = $stats ?? [])
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><x-stat-card label="العملاء" :value="number_format(data_get($overviewStats,'clients',0))" icon="fa-users" color="green" hint="إجمالي ملفات العملاء"/><x-stat-card label="القضايا النشطة" :value="number_format(data_get($overviewStats,'active_cases',0))" icon="fa-file-invoice-dollar" color="blue" hint="قضايا تحت المتابعة"/><x-stat-card label="دفعات معلقة" :value="number_format(data_get($overviewStats,'pending_payments',0))" icon="fa-clock" color="orange" hint="تحتاج إلى مراجعة"/><x-stat-card label="التحصيل المؤكد" :value="number_format((float)data_get($overviewStats,'confirmed_collections',0),2).' ج.م'" icon="fa-sack-dollar" color="purple" hint="الدفعات المعتمدة"/></div>
<div class="mt-5 grid gap-5 xl:grid-cols-2"><x-panel title="أهم مؤشرات المتابعة" subtitle="الأرقام المعروضة تعتمد على البيانات التي يرسلها المتحكم" icon="fa-gauge-high"><div class="space-y-4">@foreach([['المدفوعات المعلقة',data_get($overviewStats,'pending_payments',0),'text-warning','fa-hourglass-half'],['القضايا المتأخرة',data_get($overviewStats,'overdue_cases',0),'text-danger','fa-triangle-exclamation'],['وعود السداد النشطة',data_get($overviewStats,'active_promises',0),'text-info','fa-handshake'],['الشكاوى المفتوحة',data_get($overviewStats,'open_complaints',0),'text-accent','fa-message']] as $metric)<div class="flex items-center justify-between gap-4 rounded-xl border border-line bg-white/[0.02] p-4"><div class="flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-lg bg-white/[0.04] {{ $metric[2] }}"><i class="fa-solid {{ $metric[3] }}"></i></span><span class="text-xs font-bold text-muted">{{ $metric[0] }}</span></div><span class="text-lg font-black text-fg">{{ number_format((float)$metric[1]) }}</span></div>@endforeach</div></x-panel>
<x-panel title="الوصول السريع" subtitle="افتح الوحدات المستخدمة يوميًا" icon="fa-bolt"><div class="grid gap-3 sm:grid-cols-2">@foreach([['العملاء','clients.index','fa-users'],['المدفوعات','payments.index','fa-money-bill-transfer'],['مراجعة المدفوعات','payments.confirmations','fa-list-check'],['القضايا والقروض','loans.index','fa-file-invoice-dollar'],['التقارير','reports.index','fa-chart-column'],['الإعدادات','settings.index','fa-sliders']] as $link)<a href="{{ \Illuminate\Support\Facades\Route::has($link[1]) ? route($link[1]) : 'javascript:void(0)' }}" class="flex items-center gap-3 rounded-xl border border-line bg-white/[0.02] p-3 hover:border-brand/25 hover:bg-brand/[0.03]"><span class="grid h-9 w-9 place-items-center rounded-lg bg-brand/10 text-brand"><i class="fa-solid {{ $link[2] }}"></i></span><span class="flex-1 text-xs font-extrabold text-fg">{{ $link[0] }}</span><i class="fa-solid fa-arrow-left text-[10px] text-dim"></i></a>@endforeach</div></x-panel></div>
@endsection
